// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkFmQ0ZXLB-9uUVs9j_2qg5sxLGj1lrqI',
    appId: '1:751253771785:web:b6f73461a819570147cad8',
    messagingSenderId: '751253771785',
    projectId: 'aiflow-f5007',
    authDomain: 'aiflow-f5007.firebaseapp.com',
    storageBucket: 'aiflow-f5007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3bNVe4Qq8p2nbywZt91J8jBmWaIsRHk',
    appId: '1:751253771785:android:a53616bcd1c61f4e47cad8',
    messagingSenderId: '751253771785',
    projectId: 'aiflow-f5007',
    storageBucket: 'aiflow-f5007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_VjbCOu3jofUWLE1PtzTXebmeq9Oufc',
    appId: '1:751253771785:ios:d133edb93f37c60247cad8',
    messagingSenderId: '751253771785',
    projectId: 'aiflow-f5007',
    storageBucket: 'aiflow-f5007.firebasestorage.app',
    iosBundleId: 'com.example.aiflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP_VjbCOu3jofUWLE1PtzTXebmeq9Oufc',
    appId: '1:751253771785:ios:d133edb93f37c60247cad8',
    messagingSenderId: '751253771785',
    projectId: 'aiflow-f5007',
    storageBucket: 'aiflow-f5007.firebasestorage.app',
    iosBundleId: 'com.example.aiflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkFmQ0ZXLB-9uUVs9j_2qg5sxLGj1lrqI',
    appId: '1:751253771785:web:56c0f8a012874fbf47cad8',
    messagingSenderId: '751253771785',
    projectId: 'aiflow-f5007',
    authDomain: 'aiflow-f5007.firebaseapp.com',
    storageBucket: 'aiflow-f5007.firebasestorage.app',
  );
}
